export const posts = [
  { id: 1, title: "title 1", body: "body 1", published: true, animal: "cat" },
  { id: 2, title: "title 2", body: "body 2", published: false, animal: "dog" },
  { id: 3, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 4, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 5, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 6, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 7, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 8, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 9, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 10, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 11, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 12, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 13, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 14, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 15, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 16, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 17, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 18, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 19, title: "title 3", body: "body 3", published: true, animal: "pig" },
  { id: 20, title: "title 3", body: "body 3", published: true, animal: "pig" },
];
